import fs from 'fs'
import { join } from 'path';

export const translation = {
    ru: {
        // navbar--------------------------------------
        searchPlaceholder: "Поиск",
        phone: "+99871 202-14-41",
        services: "Услуги",
        catalog: "Каталог",
        doctors: "Врачи",
        patients: "Пациентам",
        childrenAndHearing: "Дети и слух",
        aboutUs: "О нас",
        ourAddresses: "Наши адреса",

        // home page ------------------------------------

        OurServices: "Наши услуги",
        HearingDiagnosticsInAdults: "Диагностика слуха у взрослых",
        HearingDiagnosticsInAdultsText: "Все виды обследования слуха на новейшем оборудовании Interacoustics (Дания)",
        HearingDiagnosticsInChildren: "Диагностика слуха у детей",
        HearingDiagnosticsInChildrenText: "Новейшие методы обследования слуха у детей разного возраста, в т.ч. новорожденных",
        EarPlugs: "Ушные вкладыши",
        ManufacturingOfIndividualEarMoldsForHearingAidsForAdultsAndChildren: "Изготовление индивидуальных ушных вкладышей для слуховых аппаратов взрослым и детям",
        FindTheNearestCenter: "Найти ближайший центр",
        AddressesOfMedicalCentersForDiagnosticsAndHearingCorrectionInBelarus: "Адреса медицинских центров диагностики и коррекции слуха в Беларуси",
        HearingAids: "Слуховые аппараты",
        ForGrade2HearingLoss: "При тугоухости 2 степени",
        AWideRangeOfModels: "Большой выбор моделей для помощи при нарушениях слуха умеренной степени",
        ForChildrenAndTeenagers: "Для детей и подростков",
        ForChildrenAndTeenagersText: "Слуховые решения, которые помогут обеспечить ребенку нормальное развитие речевых навыков",
        BTE: "Заушные",
        BTEText: "Простые в ношении, уходе и управлении эти модели легко скрываются за ушной раковиной и волосами",
        ForTheElderly: "Для пожилых людей",
        ForTheElderlyText: "Надежные, долговечные и простые в уходе слуховые решения для людей пожилого возраста",
        TinnitusManagement: "Управление шумом в ушах",
        TinnitusManagementText: "Эффективная звуковая терапия маскирует ушной шум и приносит моментальное облегчение",
        MadeForIPhoneAndroid: "Made for iPhone/Android",
        MadeForIPhoneAndroidText: "Звук высокого качества с вашего смартфона напрямую в слуховые аппараты",
        PowerfulAndSuperPowerful: "Мощные и супермощные",
        PowerfulAndSuperPowerfulText: "Универсальные решения для улучшения слуха при 3 и 4 степени тугоухости",
        Invisible: "Невидимые",
        InvisibleText: "Незаметное решение проблемы со слухом, с которым вы забудете о стеснении",
        Rechargeable: "Перезаряжаемые",
        RechargeableText: "Вам больше не придется беспокоиться, что слуховые аппараты могут разрядиться в неподходящий момент",
        StartYourJourneyToBetterHearing: "Начните свой путь к хорошему слуху",
        CheckYourHearing: "Проверьте свой слух",
        CheckYourHearingText: "Бесплатный онлайн-тест всего за 3 минуты поможет Вам узнать, насколько хорошо Вы слышите.",
        LearnAboutHearingLoss: "Узнайте о потере слуха",
        LearnAboutHearingLossText: "Статьи и материалы о нарушении слуха помогут распознать проблему и вовремя обратиться за помощью к сурдологу.",
        MakeAnAppointmentWithAnAudiologist: "Запишитесь к сурдологу",
        MakeAnAppointmentWithAnAudiologistText: "Запишитесь на прием к сурдологу и получите квалифицированную помощь в решении проблемы со слухом.",
        News: "Новости",
        TheLegendaryOticonMore: "Легендарный Oticon More в Беларуси",
        TheLegendaryOticonMoreText: "Слуховые аппараты нового поколения со встроенным искусственным интеллектом...",
        PreferentialLoanFromBelarusbank: "Льготный кредит от Беларусбанка",
        PreferentialLoanFromBelarusbankText: "Вам больше не придется ограничивать себя в выборе и откладывать решение проблемы со слухом...",
        OticonOpnSInGoodHearingCenters: "Oticon Opn S в Центрах хорошего слуха",
        OticonOpnSInGoodHearingCentersText: "Инновационные слуховые аппараты Otcion Opn S уже доступны для покупки в Центрах хорошего слуха...",
        HearingLossAndDementia: "Нарушение слуха и деменция",
        HearingLossAndDementiaText: "Как связаны тугоухость и развитие деменции, рассказывает Главный врач Центра хорошего слуха...",
        DiabetesAndHearingLoss: "Сахарный диабет и тугоухость",
        DiabetesAndHearingLossText: "Сахарный диабет, как фактор риска появления и развития слуховых нарушений...",
        WorkOfTheCenter: "Работа Центра в Бресте в июле",
        WorkOfTheCenterText: "Изменения в работе Центра в Бресте в период с 1 по 16 июля. Просим учитывать это при планировании..",
        IndustryNews: "Новости индустрии",
        OticonCompanion: "Oticon Companion",
        OticonCompanionText: "Новое мобильное приложение Oticon для управления слуховыми аппаратами...",
        OticonOwn: "Oticon Own",
        OticonOwnText: "Еще меньше размер, еще больше мощности! Технологии, которые изменит вашу жизнь...",
        OticonMore: "Oticon More",
        OticonMoreText: "Первый слуховой аппарат со встроенным искусственным интеллектом (DNN)...",
        OticonZircon: "Oticon Zircon",
        OticonZirconText: "Уникальные технологии Oticon BrainHearing™, которые меняют жизнь на 360 градусов...",
        CochlearBelarus: "Cochlear в Беларуси",
        CochlearBelarusText: "Хорошая новость для пользователей систем кохлеарной имплантации в Беларуси...",
        FrequentlyAskedQuestions: "Часто задаваемые вопросы",

        // Footer ------------------------------------------------
        CenterForGoodHearing: "Центр хорошего слуха",
        AboutTheCenter: "О Центре",
        AddressesOfTheCenters: "Адреса центров",
        MakeAnAppointment: "Запись на прием",
        RequestCall: "Заказать звонок",
        AskQuestion: "Задать вопрос",
        LeaveFeedback: "Оставить отзыв",
        HearingAidsForAdults: "Слуховые аппараты для взрослых",
        HearingAidsForChildren: "Слуховые аппараты для детей",
        WirelessAccessories: "Беспроводные аксессуары",
        HearingAidBatteries: "Батарейки для слуховых аппаратов",
        EarPlugs: 'Ушные вкладыши',
        CareProducts: "Средства по уходу",
        PersonalDataProcessingPolicy: "Политика обработки персональных данных",
        RegulationsonTheVideoSurveillanceSystem: "Положение о системе видеонаблюдения",
        WeAreInTouch: "Мы на связи",

        // --------------------------------------------
        // services page
        Home: "Главная",
        ContentText: "Все услуги сурдолога в одном месте. Профессиональная помощь людям с тугоухостью. Диагностика, лечение и коррекция нарушений слуха у взрослых и детей с самого рождения.",
        DiagnosticsForChildren: " Диагностика для детей",
        DiagnosticsForChildrenText: "Специалисты Центра хорошего слуха оказывают полный комплекс услуг по диагностике и коррекции нарушений слуха у взрослых и детей с рождения.",
        DiagnosticsForAdults: " Диагностика слуха для взрослых",
        DiagnosticsForAdultsText: "Все виды диагностики слуха у взрослых выполняют сурдологи с применением оборудования экспертного уровня.",
        ConsultationWithAudiologist: " Консультация врача-сурдолога",
        ConsultationWithAudiologistText: "Прием врача-сурдолога занимает по времени от 30 минут до 1 часа и проходит в несколько этапов: осмотр, отоскопия, диагностика слуха, подбор и настройка слуховых аппаратов.",
        HearingCorrectionWithHearingAids: " Коррекция слуха слуховыми аппаратами",
        HearingCorrectionWithHearingAidsText: "Коррекция и реабилитация слуха при тугоухости у взрослых, детей и пожилых людей при помощи современных слуховых аппаратов.",
        CustomEarmolds: " Индивидуальные ушные вкладыши",
        CustomEarmoldsText: "Использование индивидуального ушного вкладыша делает звучание слухового аппарата более комфортным и уменьшает риск возникновения свиста обратной связи.",
        RepairAndDiagnosticsOfHearingAids: " Ремонт и диагностика слуховых аппаратов",
        RepairAndDiagnosticsOfHearingAidsText: "Ремонт слуховых аппаратов выполняется только квалифицированным специалистом с применением оригинальных запасных частей и компонентов.",
        ReceptionOfForeignCitizens: " Прием иностранных граждан",
        ReceptionOfForeignCitizensText: "Центр хорошего слуха ведет прием пациентов из других государств по прейскуранту, действительному для граждан Беларуси.",
        OnlineHearingTest: "Проверка слуха онлайн",
        OnlineHearingTestText: "Заметили, что стали хуже слышать? Пройдите простой и быстрый онлайн-тест, который поможет узнать насколько хорошо вы слышите и разбираете речь.",
        HearingAidsInInstallments: "Слуховые аппараты в рассрочку",
        HearingAidsInInstallmentsText: "Cовременные слуховые аппараты в рассрочку 0% без переплат и участия банков всего за 1 прием.",
        PricesForMedicalServices: " Цены на медицинские услуги",
        PricesForMedicalServicesText: "Полный прейскурант цен на услуги врача-сурдолога и диагностику слуха в Минске, Бресте, Гродно, Витебске, Гомеле, Могилеве.",
        Audiometry: " Аудиометрия",
        AudiometryText: "Как и в каких случаях выполняется аудиометрия, как расшифровывается аудиограмма и какие результаты показывает. Тональная, речевая и надпороговая аудиограмма - в чем отличие.",
        HearingDiagnosticsInAdults: " Диагностика слуха у взрослых",
        HearingDiagnosticsInAdultsText: "Для оценки слуха у взрослого сурдологи проводят более 10 аудиологических тестов. Диагностика выполняется на новейшем оборудовании фирмы Interacoustics (Дания).",


        // catalog page
        CatalogText: "Команда профессионалов Центра хорошего слуха знает, как улучшить качество качество жизни людей с нарушениями слуха, используя в своей работе индивидуальный подход и внушительный ассортимент товаров для слабослышащих.",
        HearingAidstext: "Самый большой каталог современных слуховых аппаратов из Дании для людей с тугоухостью от мировых лидеров ReSound, Oticon и Widex.",
        HearingAidsForChildrenText: "Большой выбор моделей современных детских слуховых аппаратов из Дании Oticon и ReSound - от миниатюрных до ультрамощных заушных, для коррекции всех степеней тугоухости.",
        CochlearImplants: " Кохлеарные импланты",
        CochlearImplantsText: "Интеллектуальные слуховые решения и аксессуары от компании Cochlear для восстановления слуха при тугоухости.",
        HearingAidBatteriesText: "Мощные, экономичные и долговечные батарейки всех типоразмеров для слуховых аппаратов и кохлеарных имплантов по самым выгодным ценам.",
        HearingAidCareProducts: " Товары для ухода за слуховыми аппаратами",
        HearingAidCareProductsText: "Каталог содержит полный набор инструментов и аксессуаров, которые помогут вам регулярно ухаживать за слуховыми аппаратами и значительно продлить срок их службы.",
        EarPlugsText: "Качественные и надежные индивидуальные ушные вкладыши из силиконового и акрилового материала, выполненные индивидуально по слепку ушного канала.",
        WirelessAccessoriesText: "Беспроводные аксессуары расширяют и улучшают возможности Ваших слуховых аппаратов в ежедневных ситуациях (просмотр TV, вождение авто, разговоры в шуме и др.).",
        Battery: "Батарейки для слуховых аппаратов",


        // Doctors page
        OurDoctors: "Наши врачи",
        MatveevKonstantinNikolaevich: "Матвеев Константин Николаевич",
        AboutMatveevKonstantinNikolaevich: "Зав. сурдологическим отделением. Врач сурдолог-оториноларинголог I категории. Прием взрослых и детей.",
        ExpMatveevKonstantinNikolaevich: "Стаж работы: с 2007 года",
        ChicherovKonstantinValerievich: " Чичеров Константин Валерьевич",
        AboutChicherovKonstantinValerievich: "Врач сурдолог-оториноларинголог высшей категории. Ведет прием взрослых и детей.",
        ExpChicherovKonstantinValerievich: "Стаж работы: с 2002 года",
        ZasenkoIrinaLeonidovna: " Засенко Ирина Леонидовна",
        AboutZasenkoIrinaLeonidovna: "Врач сурдолог-оториноларинголог I категории. Ведет прием взрослых и детей.",
        ExpZasenkoIrinaLeonidovna: "Стаж работы: с 2002 года",
        XayrulinaSvetlanaIvanovna: " Хайрулина Светлана Ивановна",
        AboutXayrulinaSvetlanaIvanovna: "Врач сурдолог-оториноларинголог I категории. Ведет прием взрослых и детей с рождения.",
        ExpXayrulinaSvetlanaIvanovna: "Стаж работы: с 2007 года",
        MorevaElenaVasilevna: " Морева Елена Васильевна",
        AboutMorevaElenaVasilevna: "Врач сурдолог-оториноларинголог высшей категории. Ведет прием взрослых и детей.",
        ExpMorevaElenaVasilevna: "Стаж работы: с 2004 года",
        SmolikMariyaAxmedsheyxovna: " Смолик Мария Ахмедшейховна",
        AboutSmolikMariyaAxmedsheyxovna: "Врач сурдолог-оториноларинголог I категории. Ведет прием взрослых и детей.",
        ExpSmolikMariyaAxmedsheyxovna: "Стаж работы: с 2009 года",


        // --------------------------------------------------------------
        // About us Page
        OurMission: "Наша миссия",
        OurMissionText1: "Наша главная ценность это люди, которые столкнулись с проблемой нарушения слуха и нуждаются в профессиональной сурдологической помощи. Более 20 лет мы помогаем людям вернуть возможность слышать мир. Мы стремимся быть лучшими, чтобы предложить вам лучшие решения для вашего слуха. За 20 лет выросло целое поколение тех, в чью судьбу мы внесли пусть и небольшой вклад, но счастливы слышать и видеть их результаты и успехи. Мы гордимся тем, что мы делаем.",
        OurMissionText2: "Надеемся, что информация на данном ресурсе будет полезной для вас. Мы хотим быть непохожими на других и делаем то, что не удается остальным. Поэтому мы предлагаем решения с учетом ваших индивидуальных особенностей и по доступной цене. Современное оборудование, специалисты высокого уровня — все это доступно для вас в наших центрах. Это оценили наши клиенты из России, Казахстана, Украины, стран Европы и Балтии.",
        AboutUsText: "С 2001 года мы работаем во благо людей с тугоухостью, чтобы вернуть и сохранить ценный ресурс - слух.",
        Specialists: "Специалисты",
        SpecialistsText: "Команда профессионалов ежедневно помогает слабослышащим людям в решении проблем со слухом.",
        EquipmentAndTechnologies: "Оборудование и технологии",
        EquipmentAndTechnologiesText: "Технологическое оснащение центров соответствует высоким стандартам слухопротезирования.",
        PatientReviews: "Отзывы пациентов",
        PatientReviewsText: "Наши услуги соответствуют требованиям законодательства Республики Беларусь.",
        Licenses: "Лицензии и сертификаты",
        LicensesText: "Наши услуги соответствуют требованиям законодательства Республики Беларусь.",
        Contacts: "Контакты",
        ContactsText: "Центры слуха работают в Минске и областных городах ежедневно без обеда и выходных.",

        // ---------------------------------------------------------------
        // Deti i Sluh
        DetiISluhText: "Почему важно контролировать детский слух, какие причины могут повлиять на его ухудшение, как вовремя обнаружить тугоухость у ребенка и какие методы лечения существуют.",
        HearingLossInChildren: " Тугоухость у детей",
        HearingLossInChildrenText: "Выявить признаки тугоухости у ребенка в раннем возрасте - важная задача для родителей и врачей.",
        SignsOfHearing: " Признаки нарушения слуха у детей",
        SignsOfHearingText: "Для каждого периода развития ребенка характерны определенные реакции на окружающие звуки.",
        DetermineChild: " Как определить у ребенка тугоухость",
        DetermineChildText: "Первоочередная задача родителей - как можно раньше совместно с врачом-сурдологом выявить у ребенка тугоухость.",
        HowToPrepare: " Как подготовить ребенка к обследованию слуха",
        HowToPrepareText: "Как правильно подготовить ребенка к проверке слуха в зависимости от его возраста ребенка и планируемого метода обследования.",
        CorrectionOfHearing: " Коррекция тугоухости у детей",
        CorrectionOfHearingText: "Успешная коррекция тугоухости у детей ведет к развитию речи на равных с нормально слышащими сверстниками.",
        FeaturesOfHearing: " Особенности коррекции слуха у детей",
        FeaturesOfHearingText: "Схема ведения маленьких пациентов в Центрах хорошего слуха при коррекции нарушений слуха.",
        EarlyDiagnosis: " Ранняя диагностика — залог успешной реабилитации",
        EarlyDiagnosisText: "Если вы подозреваете, что ребенок плохо слышит, то важно не упустить время.",
        FailedTheAudioScreening: " Ребенок не прошел аудиоскрининг, что делать0",
        FailedTheAudioScreeningText: "Аудиоскрининг - простой, быстрый и безболезненный тест, который позволяет определить, есть ли патология в системе слуха.",
        AuditoryNeuropathy: " Слуховая (аудиторная) нейропатия",
        AuditoryNeuropathyText: "Какие факторы риска могут говорить о наличии патологии.",
        EarInfections: " Ушные инфекции у детей",
        EarInfectionsText: "Почему дети болеют отитами чаще, чем взрослые. Как понять, что у ребенка болит ухо. Какое лечение при отите. Ушные инфекции и антибиотики.",
        Achievements: " Достижения наших маленьких пациентов",
        AchievementsText: 'Раздел для родителей, чьим детям уже поставлен диагноз "тугоухость."',





    },

    uz: {
        // navbar ----------------------------
        searchPlaceholder: "Qidirish",
        phone: "+99871 202-14-41",
        services: "Xizmatlar",
        catalog: "Katalog",
        doctors: "Shifokorlar",
        patients: "Bemorlar uchun",
        childrenAndHearing: "Bolalar va eshitish",
        aboutUs: "Biz haqimizda",
        ourAddresses: "Filiallarimiz",

        //   homepage ------------------------------
        OurServices: "Bizning xizmatlarimiz",
        HearingDiagnosticsInAdults: "Kattalardagi eshitish diagnostikasi",
        HearingDiagnosticsInAdultsText: "Eng yangi Interacoustics uskunasidan foydalangan holda barcha turdagi eshitish tekshiruvlari (Daniya)",
        HearingDiagnosticsInChildren: "Bolalarda eshitish diagnostikasi",
        HearingDiagnosticsInChildrenText: "Turli yoshdagi bolalarda eshitishni tekshirishning so'nggi usullari, shu jumladan. yangi tug'ilgan chaqaloqlar",
        EarPlugs: "Quloqlar uchun maslahatlar",
        ManufacturingOfIndividualEarMoldsForHearingAidsForAdultsAndChildren: "Kattalar va bolalar uchun eshitish asboblari uchun individual quloq qoliplarini ishlab chiqarish",
        FindTheNearestCenter: "Eng yaqin markazingizni toping",
        AddressesOfMedicalCentersForDiagnosticsAndHearingCorrectionInBelarus: "Belarusiyadagi diagnostika va eshitishni tuzatish uchun tibbiy markazlarning manzillari",
        HearingAids: "Eshitish vositalari",
        ForGrade2HearingLoss: "2 daraja eshitish qobiliyatini yo'qotish uchun",
        AWideRangeOfModels: "O'rtacha eshitish qobiliyatini yo'qotishga yordam beradigan modellarning katta tanlovi",
        ForChildrenAndTeenagers: "Bolalar va o'smirlar uchun",
        ForChildrenAndTeenagersText: "Farzandingizga normal nutq qobiliyatlarini rivojlantirishga yordam beradigan eshitish echimlari",
        BTE: "BTE",
        BTEText: "Kiyinish, parvarish qilish va nazorat qilish oson, bu modellar quloq va soch orqasida osongina yashiringan",
        ForTheElderly: "Qariyalar uchun",
        ForTheElderlyText: "Keksa odamlar uchun ishonchli, bardoshli va parvarish qilish oson eshitish vositalari",
        TinnitusManagement: "Tinnitus boshqaruvi",
        TinnitusManagementText: "Samarali ovoz terapiyasi tinnitusni niqoblaydi va bir zumda yengillik keltiradi",
        MadeForIPhoneAndroid: "iPhone/Android uchun yaratilgan",
        MadeForIPhoneAndroidText: "Smartfoningizdan to'g'ridan-to'g'ri eshitish asboblaringizga yuqori sifatli ovoz",
        PowerfulAndSuperPowerful: "Kuchli va super kuchli",
        PowerfulAndSuperPowerfulText: "3 va 4 darajali eshitish qobiliyatini yaxshilash uchun universal echimlar",
        Invisible: "Ko'rinmas",
        InvisibleText: "Eshitish muammosiga aqlli yechim, bu sizni har qanday noqulaylik haqida unutishga majbur qiladi",
        Rechargeable: "Qayta zaryadlanuvchi",
        RechargeableText: "Eshitish asboblaringiz noto‘g‘ri vaqtda zaryadsizlanib qolishi haqida endi tashvishlanishingiz shart emas.",
        StartYourJourneyToBetterHearing: "Yaxshiroq eshitish uchun sayohatingizni boshlang",
        CheckYourHearing: "Eshitish qobiliyatini sinab ko'ring",
        CheckYourHearingText: "Atigi 3 daqiqada bepul onlayn test sizga qanchalik yaxshi eshitganingizni aniqlashga yordam beradi.",
        LearnAboutHearingLoss: "Eshitish qobiliyatini yo'qotish haqida bilib oling",
        LearnAboutHearingLossText: "Eshitish qobiliyatini yo'qotish haqidagi maqolalar va materiallar muammoni aniqlashga va o'z vaqtida audiologdan yordam so'rashga yordam beradi.",
        MakeAnAppointmentWithAnAudiologist: "Audiolog bilan uchrashuv tayinlang",
        MakeAnAppointmentWithAnAudiologistText: "Audiolog bilan uchrashuvga yozing va eshitish muammosini hal qilishda malakali yordam oling.",
        News: "Yangiliklar",
        TheLegendaryOticonMore: "Belarusiyada afsonaviy Oticon More",
        TheLegendaryOticonMoreText: "O'rnatilgan sun'iy intellektga ega yangi avlod eshitish apparatlari...",
        PreferentialLoanFromBelarusbank: "Belarusbankdan imtiyozli kredit",
        PreferentialLoanFromBelarusbankText: "You no longer have to limit yourself in your choices and postpone solving your hearing problem...",
        OticonOpnSInGoodHearingCenters: "Oticon Opn S yaxshi eshitish markazlarida",
        OticonOpnSInGoodHearingCentersText: "Innovatsion Oticon Opn S eshitish apparatlarini endi yaxshi eshitish markazlarida xarid qilish mumkin...",
        HearingLossAndDementia: "Eshitish qobiliyatini yo'qotish va demans",
        HearingLossAndDementiaText: "Eshitish qobiliyatini yo'qotish va demensiya rivojlanishi qanday bog'liq, deydi Yaxshi eshitish markazi bosh shifokori...",
        DiabetesAndHearingLoss: "Qandli diabet va eshitish qobiliyatini yo'qotish",
        DiabetesAndHearingLossText: "Qandli diabet eshitish buzilishlarining paydo bo'lishi va rivojlanishi uchun xavf omili sifatida...",
        WorkOfTheCenter: "Markazning Brestdagi ishi iyul oyida",
        WorkOfTheCenterText: "1 iyuldan 16 iyulgacha Brestdagi Markaz ishidagi o'zgarishlar. Iltimos, rejalashtirishda buni hisobga oling..",
        IndustryNews: "Sanoat yangiliklari",
        OticonCompanion: "Oticon Companion",
        OticonCompanionText: "Eshitish vositalarini boshqarish uchun yangi Oticon mobil ilovasi...",
        OticonOwn: "Oticon Own",
        OticonOwnText: "Hatto kichikroq o'lcham, undan ham ko'proq quvvat! Hayotingizni o'zgartiradigan texnologiyalar...",
        OticonMore: "Oticon More",
        OticonMoreText: "O'rnatilgan sun'iy intellektga (DNN) ega birinchi eshitish apparati...",
        OticonZircon: "Oticon Zircon",
        OticonZirconText: "Hayotni 360 daraja o'zgartiruvchi noyob Oticon BrainHearing™ texnologiyalari...",
        CochlearBelarus: "Cochlear Belarus",
        CochlearBelarusText: "Belarusiyada koxlear implantatsiya tizimlari foydalanuvchilari uchun xushxabar...",
        FrequentlyAskedQuestions: "Tez-tez so'raladigan savollar",

        // Footer -----------------------------------------------------------------
        CenterForGoodHearing: "Yaxshi eshitish markazi",
        AboutTheCenter: "Markaz haqida",
        AddressesOfTheCenters: "Markaz manzillari",
        MakeAnAppointment: "Uchrashuv belgilang",
        RequestCall: "Qo'ng'iroqni talab qiling",
        AskQuestion: "Savol bering",
        LeaveFeedback: "Fikr qoldiring",
        HearingAidsForAdults: "Kattalar uchun eshitish vositalari",
        HearingAidsForChildren: "Bolalar uchun eshitish vositalari",
        WirelessAccessories: "Simsiz aksessuarlar",
        HearingAidBatteries: "Eshitish moslamalari uchun batareyalar",
        EarPlugs: "Quloqlar uchun maslahatlar",
        CareProducts: "Parvarish vositalari",
        PersonalDataProcessingPolicy: "Shaxsiy ma'lumotlarni qayta ishlash siyosati",
        RegulationsonTheVideoSurveillanceSystem: "Videokuzatuv tizimi to'g'risidagi nizom",
        WeAreInTouch: "Biz aloqadamiz",

        // ------------------------------------
        // services page
        Home: "Bosh sahifa",
        ContentText: "Barcha audiolog xizmatlari bir joyda. Eshitish qobiliyatini yo'qotgan odamlar uchun professional yordam. Tug'ilgandan boshlab kattalar va bolalarda eshitish buzilishi diagnostikasi, davolash va tuzatish.",
        DiagnosticsForChildren: "Bolalar uchun diagnostika",
        DiagnosticsForChildrenText: "Yaxshi eshitish markazining mutaxassislari kattalar va tug'ilishdan boshlab bolalarda eshitish qobiliyatini tashxislash va tuzatish bo'yicha to'liq xizmatlarni taqdim etadilar.",
        DiagnosticsForAdults: "Kattalar uchun eshitish diagnostikasi",
        DiagnosticsForAdultsText: "Kattalardagi barcha turdagi eshitish diagnostikasi audiologlar tomonidan ekspert darajasidagi uskunalar yordamida amalga oshiriladi.",
        ConsultationWithAudiologist: "Audiolog bilan maslahatlashing",
        ConsultationWithAudiologistText: "Odolog bilan uchrashuv 30 daqiqadan 1 soatgacha davom etadi va bir necha bosqichda amalga oshiriladi: tekshirish, otoskopiya, eshitish diagnostikasi, eshitish vositalarini tanlash va sozlash.",
        HearingCorrectionWithHearingAids: "Eshitish vositalari bilan eshitishni tuzatish",
        HearingCorrectionWithHearingAidsText: "Zamonaviy eshitish vositalaridan foydalangan holda kattalar, bolalar va qariyalarda eshitish qobiliyatini tuzatish va reabilitatsiya qilish.",
        CustomEarmolds: "Maxsus quloq maslahatlari",
        CustomEarmoldsText: "Maxsus quloq qolipidan foydalanish eshitish moslamasining ovozini yanada qulay qiladi va fikr-mulohazalarni hushtak chalish xavfini kamaytiradi.",
        RepairAndDiagnosticsOfHearingAids: "Eshitish asboblarini ta'mirlash va diagnostika qilish",
        RepairAndDiagnosticsOfHearingAidsText: "Eshitish vositalarini ta'mirlash faqat malakali mutaxassis tomonidan original ehtiyot qismlar va butlovchi qismlardan foydalangan holda amalga oshirilishi kerak.",
        ReceptionOfForeignCitizens: "Chet el fuqarolarini qabul qilish",
        ReceptionOfForeignCitizensText: "Yaxshi eshitish markazi boshqa mamlakatlardan bemorlarni Belarus fuqarolari uchun amal qiladigan narxlar ro'yxatiga muvofiq qabul qiladi.",
        OnlineHearingTest: "Onlayn eshitish testi",
        OnlineHearingTestText: "Sizning eshitishingiz yomonlashganini payqadingizmi? Nutqni qanchalik yaxshi eshitishingiz va tushunishingiz mumkinligini aniqlashga yordam beradigan tez va oddiy onlayn testdan o'ting.",
        HearingAidsInInstallments: "Eshitish asboblari nasiyaga",
        HearingAidsInInstallmentsText: "Zamonaviy eshitish apparatlari ortiqcha to'lovlarsiz 0% bo'lib-bo'lib, atigi 1 uchrashuvda bank ishtirokida.",
        PricesForMedicalServices: "Tibbiy xizmatlar uchun narxlar",
        PricesForMedicalServicesText: "Minsk, Brest, Grodno, Vitebsk, Gomel, Mogilevda audiolog xizmatlari va eshitish diagnostikasi narxlarining to'liq ro'yxati.",
        Audiometry: "Audiometriya",
        AudiometryText: "Audiometriya qanday va qanday hollarda amalga oshiriladi, audiogramma qanday dekodlanadi va u qanday natijalarni ko'rsatadi. Ohang, nutq va chegaradan yuqori audiogramma - farq nima.",
        HearingDiagnosticsInAdults: "Kattalardagi eshitish diagnostikasi",
        HearingDiagnosticsInAdultsText: "Voyaga etgan odamning eshitish qobiliyatini baholash uchun audiologlar 10 dan ortiq audiologik testlarni o'tkazadilar. Diagnostika Interacoustics (Daniya) kompaniyasining eng yangi uskunalari yordamida amalga oshiriladi.",


        // Catalog page
        CatalogText: "Yaxshi eshitish markazining professionallar jamoasi o'z ishlarida individual yondashuv va eshitish qobiliyati zaif odamlar uchun ta'sirchan assortimentdan foydalangan holda, eshitish qobiliyati zaif odamlarning hayot sifatini qanday yaxshilashni biladi.",
        HearingAidstext: "Dunyo yetakchilari ReSound, Oticon va Widexdan eshitish qobiliyatini yo'qotgan odamlar uchun Daniyadan zamonaviy eshitish vositalarining eng katta katalogi.",
        HearingAidsForChildrenText: "Daniya Oticon va ReSound zamonaviy bolalar eshitish apparatlari modellarining katta tanlovi - miniatyuradan tortib o'ta kuchli quloq orqasigacha, eshitish qobiliyatining barcha darajalarini tuzatish uchun.",
        CochlearImplants: "Koxlear implantlar",
        CochlearImplantsText: "Eshitish qobiliyatini yo'qotganlar uchun eshitish qobiliyatini tiklash uchun Cochlear kompaniyasining aqlli eshitish yechimlari va aksessuarlari.",
        HearingAidBatteriesText: "Eshitish asboblari va koxlear implantlar uchun barcha o'lchamdagi kuchli, tejamkor va bardoshli batareyalar eng yaxshi narxlarda.",
        HearingAidCareProducts: "Eshitish vositalarini parvarish qilish mahsulotlari",
        HearingAidCareProductsText: "Katalogda sizning eshitish asboblaringizga muntazam g'amxo'rlik qilish va ularning xizmat muddatini sezilarli darajada uzaytirishda yordam beradigan asboblar va aksessuarlarning to'liq to'plami mavjud.",
        EarPlugsText: "Silikon va akril materiallardan tayyorlangan yuqori sifatli va ishonchli individual quloq uchlari quloq kanali taassurotiga ko'ra individual ravishda tayyorlanadi.",
        WirelessAccessoriesText: "Simsiz aksessuarlar kundalik vaziyatlarda (televizor ko'rish, haydash, shovqinda gaplashish va h.k.) eshitish vositalarining imkoniyatlarini kengaytiradi va yaxshilaydi.",
        Battery: "Eshitish apparati batareyalari",

        // Doctors page
        OurDoctors: "Bizning shifokorlar",
        MatveevKonstantinNikolaevich: "Matveev Konstantin Nikolaevich",
        AboutMatveevKonstantinNikolaevich: "Bosh audiologiya bo'limi. Audiolog-otolaringolog, I toifa. Kattalar va bolalarni qabul qilish.",
        ExpMatveevKonstantinNikolaevich: "Ish tajribasi: 2007 yildan beri",
        ChicherovKonstantinValerievich: "Chicherov Konstantin Valerievich",
        AboutChicherovKonstantinValerievich: "Oliy toifali audiolog-otolaringolog. Kattalar va bolalarni qabul qiladi.",
        ExpChicherovKonstantinValerievich: "Ish tajribasi: 2002 yildan beri",
        ZasenkoIrinaLeonidovna: "Zasenko Irina Leonidovna",
        AboutZasenkoIrinaLeonidovna: "Audiolog-otolaringolog, I toifa. Kattalar va bolalarni qabul qiladi.",
        ExpZasenkoIrinaLeonidovna: "Ish tajribasi: 2000 yildan beri",
        XayrulinaSvetlanaIvanovna: "Xayrulina Svetlana Ivanovna",
        AboutXayrulinaSvetlanaIvanovna: "Audiolog-otolaringolog, I toifa. U tug'ilgandan boshlab kattalar va bolalarni qabul qiladi.",
        ExpXayrulinaSvetlanaIvanovna: "Ish tajribasi: 2007 yildan beri",
        MorevaElenaVasilevna: "Moreva Elena Vasilevna",
        AboutMorevaElenaVasilevna: "Oliy toifali audiolog-otolaringolog. Kattalar va bolalarni qabul qiladi.",
        ExpMorevaElenaVasilevna: "Ish tajribasi: 2004 yildan beri",
        SmolikMariyaAxmedsheyxovna: "Smolik Mariya Axmedsheyxovna",
        AboutSmolikMariyaAxmedsheyxovna: "Audiolog-otolaringolog, I toifa. Kattalar va bolalarni qabul qiladi.",
        ExpSmolikMariyaAxmedsheyxovna: "Ish tajribasi: 2009 yildan beri",



        // ----------------------------------------------------------
        // About us Page
        OurMission: "Bizning vazifamiz",
        OurMissionText1: "Bizning asosiy qadriyatimiz eshitish qobiliyatini yo'qotish muammosiga duch kelgan va professional audiologik yordamga muhtoj odamlardir. 20 yildan ortiq vaqt davomida biz odamlarga dunyoni eshitish qobiliyatini tiklashga yordam beramiz. Biz sizning eshitishingiz uchun eng yaxshi echimlarni taklif qilish uchun eng yaxshi bo'lishga intilamiz. O‘tgan 20 yil ichida taqdirlariga oz bo‘lsada hissa qo‘shgan, ammo ularning samarasi va muvaffaqiyatlarini ko‘rib, eshitib, xursand bo‘lgan insonlardan butun bir avlod yetishib chiqdi. Biz qilayotgan ishimizdan faxrlanamiz.",
        OurMissionText2: "Umid qilamizki, ushbu resursdagi ma'lumotlar siz uchun foydali bo'ladi. Biz boshqalardan farq qilishni va boshqalar qila olmaydigan narsalarni qilishni xohlaymiz. Shuning uchun biz sizning shaxsiy ehtiyojlaringizga moslashtirilgan va arzon narxlardagi echimlarni taklif qilamiz. Zamonaviy jihozlar, yuqori saviyali mutaxassislar – bularning barchasi markazlarimizda mavjud. Bu Rossiya, Qozog'iston, Ukraina, Yevropa va Boltiqbo'yi mamlakatlaridagi mijozlarimiz tomonidan yuqori baholandi.",
        AboutUsText: "2001 yildan beri biz eshitish qobiliyatini yo'qotgan odamlar manfaati uchun qimmatli manba - eshitishni tiklash va saqlash uchun ishlamoqdamiz.",
        Specialists: "Mutaxassislar",
        SpecialistsText: "Professionallar jamoasi har kuni eshitish qobiliyati past odamlarga eshitish muammolarini hal qilishga yordam beradi.",
        EquipmentAndTechnologies: "Uskunalar va texnologiyalar",
        EquipmentAndTechnologiesText: "Markazlarning texnologik jihozlari eshitish xizmatining yuqori standartlariga javob beradi.",
        PatientReviews: "Bemorlarning sharhlari",
        PatientReviewsText: "Bizning xizmatlarimiz Belarus Respublikasi qonunchiligi talablariga javob beradi.",
        Licenses: "Litsenziyalar va sertifikatlar",
        LicensesText: "Bizning xizmatlarimiz Belarus Respublikasi qonunchiligi talablariga javob beradi.",
        Contacts: "Kontaktlar",
        ContactsText: "Minsk va viloyat shaharlarida har kuni, shu jumladan tushlik va dam olish kunlarida eshitish markazlari ishlaydi.",


        // -------------------------------------------------------------------
        // Deti i sluh
        DetiISluhText: "Nima uchun bolalarning eshitishini kuzatish muhim, qanday sabablar uning yomonlashishiga ta'sir qilishi mumkin, bolada eshitish qobiliyatini o'z vaqtida qanday aniqlash mumkin va qanday davolash usullari mavjud.",
        HearingLossInChildren: "Bolalarda eshitish halokati",
        HearingLossInChildrenText: "Bolada erta yoshda eshitish qobiliyatini yo'qotish belgilarini aniqlash ota-onalar va shifokorlar uchun muhim vazifadir.",
        SignsOfHearing: "Bolalarda eshitish qobiliyatini yo'qotish belgilari",
        SignsOfHearingText: "Bola rivojlanishining har bir davri atrof-muhit tovushlariga ma'lum reaktsiyalar bilan tavsiflanadi.",
        DetermineChild: "Bolada eshitish qobiliyati yo'qligini qanday aniqlash mumkin",
        DetermineChildText: "Ota-onalarning asosiy vazifasi - audiolog bilan birgalikda bolaning eshitish qobiliyatini imkon qadar erta aniqlash.",
        HowToPrepare: "Farzandingizni eshitish testiga qanday tayyorlash kerak",
        HowToPrepareText: "Bolaning yoshi va rejalashtirilgan tekshiruv usuliga qarab, bolani eshitish testiga qanday qilib to'g'ri tayyorlash kerak.",
        CorrectionOfHearing: "Bolalarda eshitish qobiliyatini yo'qotishni tuzatish",
        CorrectionOfHearingText: "Bolalarda eshitish qobiliyatining yo'qolishini muvaffaqiyatli tuzatish nutqni normal eshitadigan tengdoshlari bilan teng ravishda rivojlanishiga olib keladi.",
        FeaturesOfHearing: "Bolalarda eshitish korreksiyasining xususiyatlari",
        FeaturesOfHearingText: "Eshitish buzilishini tuzatish uchun yaxshi eshitish markazlarida yosh bemorlarni boshqarish sxemasi.",
        EarlyDiagnosis: "Erta tashxis muvaffaqiyatli reabilitatsiyaning kalitidir",
        EarlyDiagnosisText: "Farzandingiz eshitish qobiliyatiga ega emasligiga shubha qilsangiz, vaqtni behuda sarflamaslik kerak.",
        FailedTheAudioScreening: "Bola audio skriningdan o'tmadi, nima qilish kerak?",
        FailedTheAudioScreeningText: "Audio skrining oddiy, tez va og'riqsiz test bo'lib, eshitish tizimida patologiya mavjudligini aniqlash imkonini beradi.",
        AuditoryNeuropathy: "Eshitish (sinf) nevropatiyasi",
        AuditoryNeuropathyText: "Qanday xavf omillari patologiyaning mavjudligini ko'rsatishi mumkin.",
        EarInfections: "Bolalarda quloq infektsiyalari",
        EarInfectionsText: "Nima uchun bolalarda otit ommaviy axborot vositalari kattalarga qaraganda tez-tez uchraydi? Bolada quloq og'rig'i borligini qanday tushunish mumkin. Otit ommaviy axborot vositalarini davolash qanday? Quloq infektsiyalari va antibiotiklar.",
        Achievements: "Kichkina bemorlarimizning yutuqlari",
        AchievementsText: "Ushbu bo'lim bolalariga eshitish qobiliyatini yo'qotish tashxisi qo'yilgan ota-onalar uchun mo'ljallangan.",
    }
};

function renderFunction(params) {
    let text = fs.readFileSync(join(process.cwd(), 'database/doctor_cards.json'), 'utf-8')

    let json = JSON.parse(text)
    let objarray_ru = []
    let objarray_uz = []
    let count = 1
    for (const element of json) {
        objarray_ru.push({
            "id": count,
            "img": element.img,
            "doctorsName": translation.ru[element.doctorsName],
            "aboutDoctor": translation.ru[element.aboutDoctor],
            "experience": translation.ru[element.experience],
            "link": element.link
        })
        objarray_uz.push({
            "id": count,
            "img": element.img,
            "doctorsName": translation.uz[element.doctorsName],
            "aboutDoctor": translation.uz[element.aboutDoctor],
            "experience": translation.uz[element.experience],
            "link": element.link
        })
        count++
    }

    fs.writeFileSync(join(process.cwd(), 'database', 'doctor_cards_ru.json'), JSON.stringify(objarray_ru, null, 4))
    fs.writeFileSync(join(process.cwd(), 'database', 'doctor_cards_uz.json'), JSON.stringify(objarray_uz, null, 4))
}

renderFunction()